version: '3.8'

services:

  frontend:
    build: frontend
    ports:
      - 20080:80
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app

  backend:
    build: backend
    ports:
      - 21080:80
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app

  pgsql:
    image: postgres:16.4
    ports:
      - "25444:5432"
    environment:
      - POSTGRES_DB=management_company
      - POSTGRES_USER=management
      - POSTGRES_PASSWORD=secret

  pgsql-test:
    image: postgres:16.4
    ports:
      - "25445:5432"
    environment:
      - POSTGRES_DB=management_company_test
      - POSTGRES_USER=management_test
      - POSTGRES_PASSWORD=secret

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data

volumes:
  redis-data:
  esdata:
    driver: local